[application]

# dioxus project name
name = "fingers-and-toes"

# default platfrom
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "docs"

base_path = "https://github.com/kloki/finger-and-toes"


[web.app]

# HTML title tag content

title = "ğŸ‘ 'n ğŸ¦¶"

[web.watcher]

index_on_404 = true

watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
